env: "local"
addr: "0.0.0.0:44032"
services:
  sso:
    endpoint: "sso-app:44043"
    timeout: "5s"
  task:
    endpoint: "task-app:44045"
    timeout: "5s"
redis:
  url: "redis:6379"
  db: 0
  password: ""